### ISSUE TITLE
Problem with summons exp stages

### ISSUE THREAD

**Issue by Pietia10** [opentibia/server#47] opened 2015-03-18 07:11 UTC
When you kill a monster with summon for example lets say rat which has 5x experience. You set in exp_stages exp x100 so it means that for rat you should get 500exp that's correct without a summon.
But when you summon a monster and then kill rat you only get 400exp (200 summon 200 player).
When you for example kill cave rat which should give you 1000exp  but when summon helps you you get for example 800+ 100 summon.
When summon helps you kill rat for example you get 100 exp and summon gets 100 exp simply varies (instead of total 500)
or when you kill cave rat with summon which should give you 1000 exp you get:
300 + 300 for summon .
 So it's completly broken right now.
Keep in mind that I didn't used happy hours in this calculation.

Wiki:
Experience Gain
When killing a creature with a summon, you will only receive partial experience for the kill (minimum of 50%).
For example, if your summon causes all of the damage to kill a Rotworm, you will only receive 20 experience (half). If you personally deal some of the damage, you will receive more exp.
The formula for experience gain is:
player's exp gain + (summon's exp gain /2)
The player's experience gain is based on the player's damage.

**Comment by assassina** [comment] 2015-03-20 18:24
I've noticed an issue happening when the monster gives an experience number points who happens to be odd, due to rounding down.
For example, a rat gives 5 xp. If it is killed by a summon, then the summon counts as a half rat, which should be 2.5 xp, but is rounded as 2 xp. If the exp rate is x 100, the player (and the summon) gets 200 xp. That can be easily patched.
But your issue with the cave rat (which gives an even number of xp points), I wasn't able to reproduce it. I am always getting 750 + 750 (which is ok, due to the premmy bonus). Are you sure that you haven't edited it to give you 7 xp points (instead of the usual 10)?

**Comment by Pietia10** [comment] 2015-03-20 18:30
Nah not really  Have you tried to actually let your summoned monster hit cave rat(and you hit as well) a bit and then count total experience?

**Comment by assassina** [comment] 2015-03-21 05:14
Ok, it is happening here as well. And it is still the same issue of rounding things down. It is an easy patch. I will try to commit the patch at the next days, but I won't promise anything, I might be kind of busy with work at the next weeks, so it might take a little bit.

**Comment by assassina** [comment] 2015-03-22 03:28
It should be fixed by now. Please test it and let me know if I broke something or if there is something yet not fixed.

**Comment by Pietia10** [comment] 2015-03-22 17:19
Write on skype to me ;p

**Comment by assassina** [comment] 2015-03-22 17:38
I already commited the fix, haven't you noticed it?

**Comment by Pietia10** [comment] 2015-03-22 17:48
Ye I did I'm experiencing an issue with own summons giving some xp.

**Comment by assassina** [comment] 2015-03-23 05:17
Is it hard for players to see how much exp they have gained? But the number of gained experience points pulls out of the head of the char! What do you mean?

**Comment by Pietia10** [comment] 2015-03-23 09:09
I just checked on clean trunk seems like it works fine there so just close it , 
It's just my server again and I'm pretty sure I did made all changes .

**Comment by assassina** [comment] 2015-03-23 18:17
It has being fixed, so I am closing it now.

**Closed by assassina** 2015-03-23 18:17 UTC
Labels: bug, Legacy
